/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { HotelBookingService } from "../hotelBooking.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { HotelBookingCreateInput } from "./HotelBookingCreateInput";
import { HotelBooking } from "./HotelBooking";
import { HotelBookingFindManyArgs } from "./HotelBookingFindManyArgs";
import { HotelBookingWhereUniqueInput } from "./HotelBookingWhereUniqueInput";
import { HotelBookingUpdateInput } from "./HotelBookingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class HotelBookingControllerBase {
  constructor(
    protected readonly service: HotelBookingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: HotelBooking })
  @nestAccessControl.UseRoles({
    resource: "HotelBooking",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createHotelBooking(
    @common.Body() data: HotelBookingCreateInput
  ): Promise<HotelBooking> {
    return await this.service.createHotelBooking({
      data: {
        ...data,

        customer: data.customer
          ? {
              connect: data.customer,
            }
          : undefined,
      },
      select: {
        checkInDate: true,
        checkOutDate: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        roomType: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [HotelBooking] })
  @ApiNestedQuery(HotelBookingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "HotelBooking",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async hotelBookings(@common.Req() request: Request): Promise<HotelBooking[]> {
    const args = plainToClass(HotelBookingFindManyArgs, request.query);
    return this.service.hotelBookings({
      ...args,
      select: {
        checkInDate: true,
        checkOutDate: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        roomType: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: HotelBooking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HotelBooking",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async hotelBooking(
    @common.Param() params: HotelBookingWhereUniqueInput
  ): Promise<HotelBooking | null> {
    const result = await this.service.hotelBooking({
      where: params,
      select: {
        checkInDate: true,
        checkOutDate: true,
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        id: true,
        roomType: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: HotelBooking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HotelBooking",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateHotelBooking(
    @common.Param() params: HotelBookingWhereUniqueInput,
    @common.Body() data: HotelBookingUpdateInput
  ): Promise<HotelBooking | null> {
    try {
      return await this.service.updateHotelBooking({
        where: params,
        data: {
          ...data,

          customer: data.customer
            ? {
                connect: data.customer,
              }
            : undefined,
        },
        select: {
          checkInDate: true,
          checkOutDate: true,
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          id: true,
          roomType: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: HotelBooking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "HotelBooking",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteHotelBooking(
    @common.Param() params: HotelBookingWhereUniqueInput
  ): Promise<HotelBooking | null> {
    try {
      return await this.service.deleteHotelBooking({
        where: params,
        select: {
          checkInDate: true,
          checkOutDate: true,
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          id: true,
          roomType: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
