/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { TaxiBookingService } from "../taxiBooking.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { TaxiBookingCreateInput } from "./TaxiBookingCreateInput";
import { TaxiBooking } from "./TaxiBooking";
import { TaxiBookingFindManyArgs } from "./TaxiBookingFindManyArgs";
import { TaxiBookingWhereUniqueInput } from "./TaxiBookingWhereUniqueInput";
import { TaxiBookingUpdateInput } from "./TaxiBookingUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class TaxiBookingControllerBase {
  constructor(
    protected readonly service: TaxiBookingService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: TaxiBooking })
  @nestAccessControl.UseRoles({
    resource: "TaxiBooking",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createTaxiBooking(
    @common.Body() data: TaxiBookingCreateInput
  ): Promise<TaxiBooking> {
    return await this.service.createTaxiBooking({
      data: {
        ...data,

        customer: data.customer
          ? {
              connect: data.customer,
            }
          : undefined,
      },
      select: {
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        dropoffLocation: true,
        id: true,
        pickupLocation: true,
        pickupTime: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [TaxiBooking] })
  @ApiNestedQuery(TaxiBookingFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "TaxiBooking",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async taxiBookings(@common.Req() request: Request): Promise<TaxiBooking[]> {
    const args = plainToClass(TaxiBookingFindManyArgs, request.query);
    return this.service.taxiBookings({
      ...args,
      select: {
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        dropoffLocation: true,
        id: true,
        pickupLocation: true,
        pickupTime: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: TaxiBooking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TaxiBooking",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async taxiBooking(
    @common.Param() params: TaxiBookingWhereUniqueInput
  ): Promise<TaxiBooking | null> {
    const result = await this.service.taxiBooking({
      where: params,
      select: {
        createdAt: true,

        customer: {
          select: {
            id: true,
          },
        },

        dropoffLocation: true,
        id: true,
        pickupLocation: true,
        pickupTime: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: TaxiBooking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TaxiBooking",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateTaxiBooking(
    @common.Param() params: TaxiBookingWhereUniqueInput,
    @common.Body() data: TaxiBookingUpdateInput
  ): Promise<TaxiBooking | null> {
    try {
      return await this.service.updateTaxiBooking({
        where: params,
        data: {
          ...data,

          customer: data.customer
            ? {
                connect: data.customer,
              }
            : undefined,
        },
        select: {
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          dropoffLocation: true,
          id: true,
          pickupLocation: true,
          pickupTime: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: TaxiBooking })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "TaxiBooking",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteTaxiBooking(
    @common.Param() params: TaxiBookingWhereUniqueInput
  ): Promise<TaxiBooking | null> {
    try {
      return await this.service.deleteTaxiBooking({
        where: params,
        select: {
          createdAt: true,

          customer: {
            select: {
              id: true,
            },
          },

          dropoffLocation: true,
          id: true,
          pickupLocation: true,
          pickupTime: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
